name: PR Validation & Image Build
    on:
    pull_request:
    types: [opened, reopened, synchronize]


permissions:
contents: read
packages: write


jobs:
build-and-push:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Set up QEMU
uses: docker/setup-qemu-action@v2


- name: Set up docker buildx
uses: docker/setup-buildx-action@v3


- name: Log in to GHCR
uses: docker/login-action@v2
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}


- name: Build and push image (with registry cache)
uses: docker/build-push-action@v4
with:
context: .
file: ./Dockerfile
push: true
platforms: linux/amd64
tags: |
ghcr.io/${{ github.repository }}:pr-${{ github.event.pull_request.number }}
ghcr.io/${{ github.repository }}:candidate
cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max


- name: Run tests / lint (optional)
run: |
npm ci
npm run lint || true
npm run test || true