name: Deploy to PROD (demo runner)
on:
    push:
        branches: [main]

permissions:
    contents: read
    packages: read

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Set repository owner lowercase
              run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to GHCR
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Pull candidate image
              run: |
                  docker pull ghcr.io/${{ env.OWNER_LC }}/ci-cd-docker-caching:candidate

            - name: Run container (demo)
              run: |
                  docker ps -a --format "{{.Names}}: {{.Image}}" || true
                  docker stop next-app || true
                  docker rm next-app || true
                  docker run -d --name next-app -p 3000:3000 ghcr.io/${{ env.OWNER_LC }}/ci-cd-docker-caching:candidate

            - name: Show container logs (short)
              run: docker logs --tail 50 next-app || true
